### ISSUE TITLE
docs: add minor note on the future of this lib

### ISSUE THREAD

**Issue by micalevisk** [thoughtspile/banditypes#1]
Hi! well done

Does this lib aims to stay 400-bytes long forever? Could you please mention this in the `README.md`?

**Comment by thoughtspile** [comment]
Good question! Short answer is yes, that's the aim, and I still have around 20 bytes to spare. However, if some bugs need fixing, the size might go slightly above that. I'll think of the best way to word this.

**Comment by thoughtspile** [comment]
and it's done
