### ISSUE TITLE
Breaking bug in 0.2.4 introduce by required in object

### ISSUE THREAD

**Issue by jordan-boyer** [thoughtspile/banditypes#14]
It's seem this bug is introduce by the way the d.ts file is generated.

Because when you import the ts file directly typescript does not complain.

here the type produce by 0.2.4
```ts
export declare const object: <T = Record<string, never>>(schema: Required<T> extends infer T_1 ? { [K in keyof T_1]: Cast<T[K], unknown>; } : never) => Banditype<Simplify<Partial<T> & Pick<T, { [K_1 in keyof T]: T[K_1] extends Exclude<T[K_1], undefined> ? K_1 : never; }[keyof T]>>>;
```

and here the type produce by 0.2.3
```ts
export declare const object: <T = Record<string, never>>(schema: { [K in keyof T]: Cast<T[K], unknown>; }) => Banditype<Simplify<Partial<T> & Pick<T, { [K_1 in keyof T]: T[K_1] extends Exclude<T[K_1], undefined> ? K_1 : never; }[keyof T]>>>;
```

I'll try to look into it but I think we should remove this release for now until we can fix it

**Comment by jordan-boyer** [comment]
After investigation I found that the part that makes thing break is `Required<T> extends infer T_1`.

This only occurs when the target is an arrow function. The problem is solved when i convert the arrow function to a normal function. 

Maybe we should file an issue to the typescript team ?

Are you ok for converting arrow function to normal function ? Or only for those two function (`object` and `objectLoose`) ?

**Comment by thoughtspile** [comment]
Not sure what's going on here — would replacing `Required` with `-?:` help?

**Comment by jordan-boyer** [comment]
Thx for the fix. 

I did send a report to the typescript team for this bug because it's only present starting typescript 4.7 

https://github.com/microsoft/TypeScript/issues/53109
