### ISSUE TITLE
Function fail throw an error

### ISSUE THREAD

**Issue by jordan-boyer** [thoughtspile/banditypes#2]
```
node_modules/.pnpm/banditypes@0.2.2/node_modules/banditypes/dist/cjs/index.cjs:19
const fail = () => "bad banditype"();
                                  ^
TypeError: "bad banditype" is not a function
```
why trying to execute a function call on a string ?  
https://github.com/thoughtspile/banditypes/blob/0b992f7e9ea04894fde8c1215eb6e85e1fcaefea/src/index.ts#L24

**Comment by thoughtspile** [comment]
It's quirky, but it saves 20 bytes, and the errors don't contain any useful detail anyways. I might reconsider this design decision later.

**Comment by jordan-boyer** [comment]
I'm not sure to understand here but is this not enough ? 
```ts
export const fail = () => { throw new Error("bad banditype") };
```

**Comment by jordan-boyer** [comment]
I'll close the issue I did see the article explaining why =)
